### ISSUE TITLE
Implement sound

### ISSUE THREAD

**Issue by fhoedemakers** [fhoedemakers/PicoSystem_InfoNes#3]
The PicoSystem has a simple piezo speaker/buffer. I'm not sure how this can be accomplished, so help is welcome.

**Comment by shuichitakano** [comment]
I think you can achieve reasonable sound quality using delta-sigma modulation (I think there was an implementation in pico-extra), but piezoelectric speakers can generate heat and burn out if driven at high frequencies.
Since the specifications of the speaker are not known to us, it is better to remove the back cover and watch the temperature when implementing sound playback.

**Comment by fhoedemakers** [comment]
> I think you can achieve reasonable sound quality using delta-sigma modulation (I think there was an implementation in pico-extra), but piezoelectric speakers can generate heat and burn out if driven at high frequencies. Since the specifications of the speaker are not known to us, it is better to remove the back cover and watch the temperature when implementing sound playback.

Thanks for you suggestion, much appreciated! I have little to none knowledge of sound programming. 
So i am leaving this issue open for now.

Again, thank you!

**Comment by Layer812** [comment]
I’ve just implemented sound function on your code, please try it.
It works like this.
https://twitter.com/layer812/status/1680968382781464576
# I use some NSF files to conver NES rom.

**Comment by fhoedemakers** [comment]
Sound implemented by @Layer812 #12
